version: "3"
volumes:
  vendor-store:
  node_modules-store:
services:
  web:
    image: nginx:latest
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports: ["8080:80"]
    depends_on: ["app"]
  app:
    build: ./docker/php
    volumes:
      - .:/var/www/html
      - vendor-store:/var/www/html/vendor
      - node_modules-store:/var/www/html/node_modules
    depends_on: ["mysql"]
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: example_shop
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/mysql:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf